name: Run OT Script

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (you can change this if needed)
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '45 3 * * *'  # This will run the workflow at 3:45 AM UTC, which is 9:15 AM IST

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt

    - name: Run Python script
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}  # Pass MongoDB URL secret
      run: |
        python file.py 
